version: '3'

services:
  app:
    build: .
    ports:
      - "11001:8081"
    environment:
      - PORT=8081
      - REQUEST_PROXY=${REQUEST_PROXY:-}
    volumes:
      - ./:/app
    restart: unless-stopped
